name: Update Luxembourg Public Holidays

on:
  schedule:
    - cron: "0 0 1 1 *" # Runs yearly on January 1st at midnight
  workflow_dispatch: # Allow manual triggering

jobs:
  update-holidays:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install icalendar

      - name: Run holiday update script
        env:
          YEARS_IN_PAST: 10
          YEARS_IN_FUTURE: 10

        run: python calendar-generators/luxembourg-public-holidays-ical-gen.py

      # Commit the changed file(s) back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: Automated update of Luxembourg public holidays
          commit_user_email: actions@github.com
          commit_author: Github actions <actions@github.com>